matrix:
  include:
    - dist: bionic
      env: FISH=2
      addons:
        apt:
          sources:
            - sourceline: "ppa:fish-shell/release-2"
          packages:
            - fish
    - dist: bionic
      env: FISH=3
      addons:
        apt:
          sources:
            - sourceline: "ppa:fish-shell/release-3"
          packages:
            - fish
    - os: osx
      env: FISH=3
      addons:
        homebrew:
          packages:
            - fish # --> latest, i.e. >=3.0.2
          update: true # TODO: build should be green without, but isn't

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - bundle install --gemfile=test/Gemfile --no-cache
  - uname -a; fish --version; sdk version; ruby --version; cucumber --version

install:
  - mkdir -p "${HOME}"/.config/fish/{completions,conf.d,functions}
  - cp completions/* "${HOME}"/.config/fish/completions/
  - cp conf.d/* "${HOME}"/.config/fish/conf.d/
  - cp functions/* "${HOME}"/.config/fish/functions/

script:
  - (cd test && cucumber)
  # TODO: Migrate these to Cucumber:
  - fish test/reinitialize.fish
  - fish -c "sdk install crash 1.3.0; and sdk uninstall crash 1.3.0" > /dev/null && fish test/check_for_path_zombies.fish
  - bash test/remove_sdkman.sh > /dev/null && fish -c "echo 'y' | sdk" > /dev/null && fish -c "sdk version"
