name: Tests

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  tests:
    name: "Scenarios"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      # NB: We have a Docker setup for testing -- why do all this?
      #     Because we want to confirm it runs on macOS, and
      #     there are no Docker images based on frickin' macOS.

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4

      - name: Install Test Dependencies
        working-directory: test
        run: |
          gem install bundler
          bundle install

      - name: Install SDKMAN!
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk version

      - name: Install fish
        uses: fish-actions/install-fish@4bb37a71daebb76c6fb7d83771cff31b8a78c28e # v1.2.0

      - name: Install sdkman-for-fish
        shell: fish "{0}"
        run: |
          fish --version
          curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source \
              && fisher install jorgebucaran/fisher
          fisher install .

      - name: Confirm install
        shell: fish "{0}"
        run: |
          cat /etc/os-release || sw_vers || true
          fish --version
          fisher --version
          sdk version

      - name: Run Tests
        working-directory: test
        env:
          RUNNING_IN_CONTAINER: yessir
        run: |
          cucumber --publish-quiet --tags "not @pending"

  confirm-installation:
    name: "Check fisher install"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
    steps:
      - name: Install fish
        uses: fish-actions/install-fish@4bb37a71daebb76c6fb7d83771cff31b8a78c28e # v1.2.0

      - name: Install SDKMAN!
        run: |
          curl -s "https://get.sdkman.io" | bash

      - name: Install fisher
        shell: fish "{0}"
        run: |
          fish --version
          curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source \
              && fisher install jorgebucaran/fisher
          fisher --version

      - name: Install sdkman-for-fish
        shell: fish "{0}"
        run: |
          fisher install reitzig/sdkman-for-fish@${{ github.sha }}

      - name: Confirm install
        shell: fish "{0}"
        run: |
          cat /etc/os-release || sw_vers || true
          fish --version
          fisher ls
          sdk version
