name: Tests

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  tests:
    name: "Scenarios"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-20.04'
          - 'macos-latest'
    steps:
      - uses: actions/checkout@v2

      # NB: We have a Docker setup for testing -- why do all this?
      #     Because we want to confirm it runs on macOS, and
      #     there are no Docker images based on frickin' macOS.

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Test Dependencies
        working-directory: test
        run: |
          gem install bundler
          bundle install

      - name: Install SDKMAN!
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk version

      - name: Install fish
        # TODO: Change to recent version, when the maintainer creates a tag
        uses: fish-actions/install-fish@d6d9d26231a15f8d9a6b3e74b3db45512440e3e8

      - name: Install sdkman-for-fish
        shell: fish "{0}"
        run: |
          fish --version
          curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
          fisher install .

      - name: Confirm install
        shell: fish "{0}"
        run: |
          fish --version
          sdk version

      - name: Run Tests
        working-directory: test
        run: |
          cucumber --publish-quiet

  confirm-installation:
    name: "Check fisher install"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-20.04'
          - 'macos-latest'
    steps:
      - name: Install fish
        #uses: fish-actions/install-fish@v1.2.0
        uses: fish-actions/install-fish@master # TODO: change back after #2

      - name: Install SDKMAN!
        run: |
          curl -s "https://get.sdkman.io" | bash

      - name: Install fisher
        shell: fish "{0}"
        run: |
          fish --version
          curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
          fisher --version

      - name: Install sdkman-for-fish
        shell: fish "{0}"
        run: |
          fisher install reitzig/sdkman-for-fish@${{ github.sha }}

      - name: Confirm install
        shell: fish "{0}"
        run: |
          fisher ls
          sdk version
